language: node_js
node_js:
- '8'
before_install:
- stty cols 80
env:
  global:
  - secure: bMFyeHT7K0Z+gZ8hUjcEiFyBU3l6lNHV7TBs3g3qZZGrE6VJryKYEETuC1gG4+aSaz2ogVh6w3Rztu6noFzxYJR2Uhqm0w2FgEvCJeZmCNb+cLSNh9XxFPFp70MfV/zo1nyEAF91jlVTj9kXCCgw9gvCmeKJxyurLQZ9rUS8ADP7eylXtPb2Iu6TDUBThD8czM7VWyLoD7MPEuVDjULaBTRtaZTNOa6HuqbWEr6NbDYg7S4XLgo9Sbkm9w4gZIy8Y1eRwXi5GzcV1jylxWN4lf4FSDhNU7tRfA4BV1cLU/3VoNwsgx8JXo1+ZS7oLdkt5GxK+3o3AGM860/5D6bvobiLG8DSZjLQK+aOWbDAxLRiEA+LkvF3gNAWiAvmkxOd+iVHqFvqNBDUjPN5WOp+qNqyawazO35sr4DdXolrNKEFYihDYH4+i8X5Iwgy9Pxewko1HR5eHG8THQLEAdCOrVsFfPaT+1mbfzyk3KSomvLEd8NsqKjpj1yVwi/Lwwal5WpnKAS4HEyps8ov5K/rIx+haMrRfmPf4Opzzj9+C1N46V2HUFDPEym75RbI+YdT4h4Zc07M91cfzgvTGq0hMzuu79vH5DLMXymxRWS5U2WqbHXu1ohwOro+qXl8PtQy+AAZt6yY1CoASIVnpbzu0yD20/CjR2/aiUfvaJOVk4g=
dist: trusty
sudo: required
addons:
  firefox: stable
  chrome: stable
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- npm install -g concurrently@3.1.0
script:
- npm run build_knockout_dev
- npm run build_knockout_prod
- npm run build_react_dev
- npm run build_react_prod
- npm run build_angular_dev
- npm run build_angular_prod
- npm run build_jquery_dev
- npm run build_jquery_prod
- npm run build_vue_dev
- npm run build_vue_prod
before_deploy: tar -zcvf xformjs.tar.gz packages
deploy:
  - provider: releases
    file:
    - xformjs.tar.gz
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: chmod +x ./deploy_npm.sh && ./deploy_npm.sh
    skip_cleanup: true
    on:
      tags: true
    api_key:
      secure: bMFyeHT7K0Z+gZ8hUjcEiFyBU3l6lNHV7TBs3g3qZZGrE6VJryKYEETuC1gG4+aSaz2ogVh6w3Rztu6noFzxYJR2Uhqm0w2FgEvCJeZmCNb+cLSNh9XxFPFp70MfV/zo1nyEAF91jlVTj9kXCCgw9gvCmeKJxyurLQZ9rUS8ADP7eylXtPb2Iu6TDUBThD8czM7VWyLoD7MPEuVDjULaBTRtaZTNOa6HuqbWEr6NbDYg7S4XLgo9Sbkm9w4gZIy8Y1eRwXi5GzcV1jylxWN4lf4FSDhNU7tRfA4BV1cLU/3VoNwsgx8JXo1+ZS7oLdkt5GxK+3o3AGM860/5D6bvobiLG8DSZjLQK+aOWbDAxLRiEA+LkvF3gNAWiAvmkxOd+iVHqFvqNBDUjPN5WOp+qNqyawazO35sr4DdXolrNKEFYihDYH4+i8X5Iwgy9Pxewko1HR5eHG8THQLEAdCOrVsFfPaT+1mbfzyk3KSomvLEd8NsqKjpj1yVwi/Lwwal5WpnKAS4HEyps8ov5K/rIx+haMrRfmPf4Opzzj9+C1N46V2HUFDPEym75RbI+YdT4h4Zc07M91cfzgvTGq0hMzuu79vH5DLMXymxRWS5U2WqbHXu1ohwOro+qXl8PtQy+AAZt6yY1CoASIVnpbzu0yD20/CjR2/aiUfvaJOVk4g=
notifications:
  email:
    recipients:
    - papu.bhattacharya@synectiks.com
