language: node_js
node_js:
- '8'
before_install:
- stty cols 80
env:
  global:
  - secure: tPxzI4Oj49ted203tBk9tle6Z1oPBPg3pebK5cGVpHdOygFF8AyYtQ+GeipK0Pd1ApeyLCO+DLNVbkGg/JPPRQfFmw9/47pjBNGEOlyGlJSaXYbVsFSIOJntgC29DLcaTuvdyAjKYOcx1DK/D2azup7XxGXDhQyZhF7Xk8/8DXXPUpbDg1yMs2eJWSC87qBrb7kUyUioGWdPW47n9ua1njC7J4+KNM1I/745NFy0q5R31EF/6LUFLun2dQecSVjCC6+WIDTVkutlyaHMKGeAMVjsa3mu7nzZzmYMo/sGl5s6J4HXxLTxQYKuJD7Z1pJWCxX1q6hUHMJgabuUd+3l/h+HIXDBHkyWMVo8f1+WanS8u80GTOqQ4JXRprpRGDrAVv/+GiDXLucIjno5ivBne2TSbmX3UL+49MTh2BC7mETDZPBjlwDRMG9iKRTdrbL20kJOmyP+dSflt3tlfUEpF+Wfdb0YWrwA9n/48OYy5kXRa1wxhUN1ct1HvLENQYQFyEhbIJWNjbZNzeRVKgANprazTpC20b1/JDZP6Hf1LtjriHFxhe3PcZeB4UYk2ADqDR03BMoDSOyFqrImoWTOaDNbbaL1unCqu82NLnshnksUR+Xko7/ho0RX0GJ3JQqP/THWuKoj7fIZO49i09Pkk409sQtIpIw3d4nu0SlpRBE=
  matrix:
    secure: tPxzI4Oj49ted203tBk9tle6Z1oPBPg3pebK5cGVpHdOygFF8AyYtQ+GeipK0Pd1ApeyLCO+DLNVbkGg/JPPRQfFmw9/47pjBNGEOlyGlJSaXYbVsFSIOJntgC29DLcaTuvdyAjKYOcx1DK/D2azup7XxGXDhQyZhF7Xk8/8DXXPUpbDg1yMs2eJWSC87qBrb7kUyUioGWdPW47n9ua1njC7J4+KNM1I/745NFy0q5R31EF/6LUFLun2dQecSVjCC6+WIDTVkutlyaHMKGeAMVjsa3mu7nzZzmYMo/sGl5s6J4HXxLTxQYKuJD7Z1pJWCxX1q6hUHMJgabuUd+3l/h+HIXDBHkyWMVo8f1+WanS8u80GTOqQ4JXRprpRGDrAVv/+GiDXLucIjno5ivBne2TSbmX3UL+49MTh2BC7mETDZPBjlwDRMG9iKRTdrbL20kJOmyP+dSflt3tlfUEpF+Wfdb0YWrwA9n/48OYy5kXRa1wxhUN1ct1HvLENQYQFyEhbIJWNjbZNzeRVKgANprazTpC20b1/JDZP6Hf1LtjriHFxhe3PcZeB4UYk2ADqDR03BMoDSOyFqrImoWTOaDNbbaL1unCqu82NLnshnksUR+Xko7/ho0RX0GJ3JQqP/THWuKoj7fIZO49i09Pkk409sQtIpIw3d4nu0SlpRBE=
dist: trusty
sudo: required
addons:
  firefox: stable
  chrome: stable
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- npm install -g concurrently@3.1.0
script:
- npm run build_knockout_dev
- npm run build_knockout_prod
- npm run build_react_dev
- npm run build_react_prod
- npm run build_angular_dev
- npm run build_angular_prod
- npm run build_jquery_dev
- npm run build_jquery_prod
- npm run build_vue_dev
- npm run build_vue_prod
before_deploy: tar -zcvf xformjs.tar.gz packages
deploy:
- provider: releases
  file:
  - xformjs.tar.gz
  skip_cleanup: true
  on:
    tags: true
- provider: script
  script: chmod +x ./deploy_npm.sh && ./deploy_npm.sh
  skip_cleanup: true
  email: papu.bhattacharya@synectiks.com
  api_key:
    secure: cKglgiqRmE7QHfrEYZVGi320nJgQJG72T1Dpoymow+bPS6Z36x79sPunK+60ePnZWrXgBOo9NqiKV1vyEbojkhHVFu6WX0N2Tl4X574khftxMzIjd9JTZqccnmLQsTJXoM/lt7MDrJQLeJWO4bR26xscyh7fNXvaXXlhp5fjgY12NJGCiXeFMGItNPbSnvOxaus+Fuzb9rkEUSvQnIJQEqI94fKJCrmvpZgulb736kFN3Q3yihMkLfyIDo8+4U0g13rZekhnV9+0PoBODATw+5dUHQ6fJ9rt65g7OKdIQdW8pN1HVpVx4KL33im1x0hyUnmlGGZqQ8xUT5TRhIgE8c/agRev7+mrW3lNqVv2jdjp/cfUmdcClO5rOgAJ10jtbom1RqOH+kA28IE0APqYfjFg3Zo/mcXvAkubOxx8Vghu8O3GZkdk2sKecfJ9oNDpsSzfIlYYPg+3qoEJVArTMg9q2FHBdc6bKp6zotdHpu2fuidD35tHAMz9NQjxvs89Nrtfb8TQh6+ZeMN51MbEA+3FuZ9e4XhhhE/A2kUoVzjSL5bGEIWlBiW51orcF5nQKALq8FWrQurWkbT1u1UxiqFlvoq6LbaGmUeAjf/KlJem0+/QoS433KPARaf/d+3T/QfYQ5dkANjaf7Gi/4QDkVnn/fYRnn7ktiuSmCnhUDM=
  on:
    tags: true
  repo: xformation/xformjs
notifications:
  email:
    recipients:
    - papu.bhattacharya@synectiks.com
